version: '3'

services:
  database:
    container_name: event-platform-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event-platform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: event-platform-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env

  frontend:
    container_name: event-platform-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env

volumes:
  postgres_data:
