name: Frontend CD

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['frontend/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/event-platform-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          build-args: |
            NEXT_PUBLIC_APP_API_URL=${{ secrets.NEXT_PUBLIC_APP_API_URL }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create environment file
        run: echo "${{ secrets.FRONTEND_ENV }}" > .env.frontend

      - name: Deploy to DigitalOcean Droplet
        env:
          DO_SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USERNAME: ${{ secrets.DO_USERNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DO_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DO_HOST >> ~/.ssh/known_hosts

          scp -i ~/.ssh/id_rsa docker-compose.prod.yml .env.frontend $DO_USERNAME@$DO_HOST:~/event-platform/

          ssh -i ~/.ssh/id_rsa $DO_USERNAME@$DO_HOST << EOF
            cd ~/event-platform

            sed -i '/FRONTEND_IMAGE/d' .env
            echo "FRONTEND_IMAGE=${{ steps.meta.outputs.tags }}" >> .env
            
            docker-compose -f docker-compose.prod.yml pull frontend
            docker-compose -f docker-compose.prod.yml up -d --no-deps frontend
          EOF
