name: Infrastructure CI/CD

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['infra/**']
  pull_request:
    branches: ['main']
    paths: ['infra/**']

defaults:
  run:
    working-directory: infra

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Create SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create terraform.auto.tfvars
        run: |
          echo "do_token = \"${{ secrets.DO_TOKEN }}\"" > terraform.auto.tfvars
          echo "pvt_key = \"~/.ssh/id_rsa\"" >> terraform.auto.tfvars
          terraform fmt terraform.auto.tfvars

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Clean up SSH Key
        if: always()
        run: rm -f ~/.ssh/id_rsa
